#!/bin/bash

export CIRCOMPARA_HOME=$(dirname $(readlink -f $0))

TOOLS_DIR=$CIRCOMPARA_HOME/tools
export TRIMMOMATIC=$TOOLS_DIR/Trimmomatic-0.36/trimmomatic-0.36.jar

export PATH=$CIRCOMPARA_HOME/bin:$PATH

export PYTHONPATH="$PYTHONPATH:$TOOLS_DIR/CIRCexplorer/lib/python2.7/site-packages/:$TOOLS_DIR/biopython/lib/python2.7/site-packages/:$TOOLS_DIR/HTSeq-0.6.1p1/lib/python2.7/site-packages/"

export R_LIBS="$CIRCOMPARA_HOME/tools/R_libs"

scons -f $CIRCOMPARA_HOME/src/junk2_circpipe_multisample $1 

