#!/bin/bash

export CIRCOMPARA_HOME=$(dirname $(readlink -f $0))

## install Scons
mkdir $CIRCOMPARA_HOME/tools
cd $CIRCOMPARA_HOME/tools
wget -N -c http://prdownloads.sourceforge.net/scons/scons-local-2.5.0.tar.gz
mkdir -p scons
tar -xf scons-local-2.5.0.tar.gz -C scons
ln -s $CIRCOMPARA_HOME/tools/scons/scons.py $CIRCOMPARA_HOME/bin/scons
cd -

cd $CIRCOMPARA_HOME/bin
ln -s ../src/*.py .
ln -s ../src/*.R .
cd -

export PATH=$CIRCOMPARA_HOME/bin/:$PATH

## export environment variable for local R repository
export R_LIBS="$CIRCOMPARA_HOME/tools/R_libs"

## install other tools
scons -i -f $CIRCOMPARA_HOME/src/junk2_install_tools_circpipe $1 
