#!/bin/bash

export JUNK2_HOME=$(dirname $(readlink -f $0))

## install Scons
mkdir $JUNK2_HOME/tools
cd $JUNK2_HOME/tools
wget -N -c http://prdownloads.sourceforge.net/scons/scons-local-2.5.0.tar.gz
mkdir -p scons
tar -xf scons-local-2.5.0.tar.gz -C scons
ln -s $JUNK2_HOME/tools/scons/scons.py $JUNK2_HOME/bin/scons
cd -

cd $JUNK2_HOME/bin
ln -s ../src/*.py .
ln -s ../src/*.R .
cd -

export PATH=$JUNK2_HOME/bin/:$PATH

## install other tools
scons -i -f $JUNK2_HOME/src/junk2_install_tools_circpipe $1 
