---
title: 'CirComPara: differential gene expression by Cuffdiff'
date: "`r Sys.Date()`"  
output: 
  html_document: 
    keep_md: no
    number_sections: yes
    toc: yes
    toc_depth: 2
    toc_float: 
      collapsed: false
      smooth_scroll: true
    theme: "readable"
---

```{r global_options, include=FALSE}
## variables to be defined in parent frame
# results.dir <- "cuffdiff/"
# meta.file <- "read_groups.info"
# gene.de.file <- "gene_exp.diff"
# child.Rmd <- $SCONSCRIPT_HOME/_lindiffexp.Rmd

library(data.table)
library(knitr)

dir.create(path = results.dir, showWarnings = F, recursive = T)
knitr::opts_chunk$set(fig.width = 7, 
                      fig.height = 4, 
                      dev = c('png'), 
                      fig.pos = "center",
                      fig.path = file.path(results.dir, paste0('Figs_deg_cuffdiff', .Platform$file.sep)),
                      echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE)

knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = results.dir)
```

```{r load data, include=FALSE}
if(meta.file != ""){
    gene_meta <- fread(meta.file, colClasses = c("character", "factor", "character", 
                                                  "numeric", "numeric", "numeric", 
                                                  "numeric"))
    gene_meta[, sample_id := sub("cuffquant/(.*)_hisat2.*", "\\1", file)]
}

gene.de <- fread(gene.de.file)[status == "OK", ]
## CAVEAT !!! Cuffdiff considers the fold change as sample_2/sample_1, that is like considering the sample_2 vs. sample_1 contrast
## Because of this, positive log2(fold_change) values are to be considered as "sample_2 is up in sample_2 vs. sample_1", but as 
## "sample_2 is down in sample_1 vs. sample_2" contrast, which is as we intended the comparisons
gene.de[, `:=`(gene_id = test_id, contrast = paste(sample_1, "vs", sample_2), 
               `log2(fold_change)` = as.numeric(`log2(fold_change)`)*-1,
               avgFPKM = round((value_1 + value_2)/2, 4))]
gene.de[status != "OK", `:=`(significant = NA)]

```

```{r, child=child.Rmd}
```