---
title: 'CirComPara: differential gene expression by DESeq2'
date: "`r Sys.Date()`"  
output: 
  html_document: 
    keep_md: no
    number_sections: yes
    toc: yes
    toc_depth: 2
    toc_float: 
      collapsed: false
      smooth_scroll: true
    theme: "readable"
editor_options: 
  chunk_output_type: console
---

```{r global_options, include=FALSE}
## variables to be defined in parent frame
# results.dir <- "ballgown/"
# meta.file <- "meta.csv"
# gene.de.file <- "any"
# gene.expr <- "any"
# child.Rmd <- $SCONSCRIPT_HOME/_lindiffexp.Rmd
sig.thr <- .1

library(data.table)
library(knitr)

dir.create(path = results.dir, showWarnings = F, recursive = T)
knitr::opts_chunk$set(fig.width = 7, 
                      fig.height = 4, 
                      dev = c('png'), 
                      fig.pos = "center",
                      # fig.path = file.path(results.dir, paste0('Figs_deg_DESeq2', .Platform$file.sep)),
                      echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE)

knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = results.dir)
```

```{r load data}
if(!grepl("DESeq failed", readLines(gene.de.file, n = 1))){
    gene.de <- fread(gene.de.file)[, gene_id := V1][, V1 := NULL]
    
    gene_meta <- unique(fread(meta.file)[, .(sample_id = sample, condition)])
    
    gene.de[, avgFPKM := baseMean]
    
    gene.de$contrast <- paste(unique(gene_meta$condition), collapse = " vs ")
    
    gene.de <- gene.de[, .(gene_id, 
                           gene = gene_id,
                           p_value = pvalue, 
                           q_value = padj, 
                           "log2(fold_change)" = log2FoldChange,
                           significant = ifelse(padj <= sig.thr, "yes", "no"),
                           contrast = "A vs B",
                           avgFPKM)]
}else{
    child.Rmd <- file.path(dirname(child.Rmd), "_empty.Rmd")
    gene.de.tab.filename <- file.path(results.dir, "DEG_tests_by_contrast.csv")
    write.csv(data.frame(), file = gene.de.tab.filename, row.names = F)
}
```

```{r, child=child.Rmd}
```


